CREATE TABLE [test].[org_emp_vw] (
    [id]                              BIGINT          NULL,
    [ldap_login]                      NVARCHAR (100)  NULL,
    [employee_full_name]              NVARCHAR (201)  NULL,
    [line_manager_id]                 BIGINT          NULL,
    [line_manager]                    NVARCHAR (201)  NULL,
    [phone_number]                    NVARCHAR (100)  NULL,
    [email]                           NVARCHAR (150)  NULL,
    [position]                        NVARCHAR (150)  NULL,
    [location]                        NVARCHAR (200)  NULL,
    [pg_user_name_deprecated]         NVARCHAR (100)  NULL,
    [pg_t_number_deprecated]          NVARCHAR (15)   NULL,
    [gender_code]                     NVARCHAR (100)  NULL,
    [nationality]                     NVARCHAR (150)  NULL,
    [role]                            NVARCHAR (4000) NULL,
    [active_ind]                      BIT             NULL,
    [functional_manager_id]           BIGINT          NULL,
    [functional_manager]              NVARCHAR (201)  NULL,
    [employment_date]                 DATE            NULL,
    [contract_termination_date]       DATE            NULL,
    [contract_type]                   NVARCHAR (100)  NULL,
    [approval_required]               BIT             NULL,
    [legal_entity]                    NVARCHAR (100)  NULL,
    [fte]                             DECIMAL (6, 3)  NULL,
    [org_unit_id]                     BIGINT          NULL,
    [org_unit_name]                   NVARCHAR (100)  NULL,
    [team_id]                         BIGINT          NULL,
    [team_name]                       NVARCHAR (100)  NULL,
    [delivery_team_id]                BIGINT          NULL,
    [delivery_team_name]              NVARCHAR (100)  NULL,
    [senior_delivery_team_id]         BIGINT          NULL,
    [senior_delivery_team_name]       NVARCHAR (100)  NULL,
    [sub_bu_id]                       BIGINT          NULL,
    [sub_bu_name]                     NVARCHAR (100)  NULL,
    [bu_id]                           BIGINT          NULL,
    [bu_name]                         NVARCHAR (100)  NULL,
    [create_ip_ind]                   BIT             NULL,
    [gender]                          VARCHAR (10)    NULL,
    [photo_ind]                       BIT             NULL,
    [allow_photo_usage_ind]           BIT             NULL,
    [primary_competency_name]         NVARCHAR (150)  NULL,
    [country]                         NVARCHAR (200)  NULL,
    [city]                            NVARCHAR (200)  NULL,
    [country_work_location]           NVARCHAR (200)  NULL,
    [city_id]                         BIGINT          NULL,
    [country_id]                      BIGINT          NULL,
    [ad_object_id]                    NVARCHAR (100)  NULL,
    [az_ad_object_id]                 NVARCHAR (100)  NULL,
    [az_ad_account_enabled_ind]       BIT             NULL,
    [leave_ind]                       BIT             NULL,
    [country_work_location_id]        BIGINT          NULL,
    [team_leader_ind]                 BIT             NULL,
    [team_owner_ind]                  BIT             NULL,
    [management_community_member_ind] BIT             NULL,
    [org_unit_area]                   NVARCHAR (1000) NULL,
    [project_manager_ind]             BIT             NULL,
    [service_level_manager_ind]       BIT             NULL,
    [competency_name]                 NVARCHAR (100)  NULL,
    [role_name]                       NVARCHAR (100)  NULL,
    [seniority_id]                    BIGINT          NULL,
    [seniority_name]                  NVARCHAR (200)  NULL,
    [technical_account_ind]           BIT             NULL,
    [position_id]                     BIGINT          NULL,
    [creation_at]                     DATETIME2 (7)   NULL,
    [external_ind]                    BIT             NULL,
    [external_type]                   NVARCHAR (1000) NULL,
    [vendor_ind]                      BIT             NULL,
    [shift_time]                      NVARCHAR (100)  NULL,
    [resource_row_id]                 BIGINT          NULL,
    [postal_code]                     NVARCHAR (20)   NULL,
    [draft_profile_ind]               BIT             NULL
);
GO

