CREATE TABLE [test].[org_emp] (
    [id]                                         BIGINT          NULL,
    [ldap_login]                                 NVARCHAR (100)  NULL,
    [last_name]                                  NVARCHAR (100)  NULL,
    [first_name]                                 NVARCHAR (100)  NULL,
    [line_manager_id]                            BIGINT          NULL,
    [photo_ind]                                  BIT             NULL,
    [phone_number]                               NVARCHAR (100)  NULL,
    [email]                                      NVARCHAR (150)  NULL,
    [position_id]                                BIGINT          NULL,
    [location]                                   NVARCHAR (100)  NULL,
    [non_employee_ind]                           BIT             NULL,
    [work_experience]                            INT             NULL,
    [pg_walmart_cda_valid_deprecated]            DATE            NULL,
    [pg_t_number_deprecated]                     NVARCHAR (15)   NULL,
    [pg_user_name_deprecated]                    NVARCHAR (100)  NULL,
    [gender_code]                                NVARCHAR (100)  NULL,
    [nationality_id]                             BIGINT          NULL,
    [maiden_name]                                NVARCHAR (100)  NULL,
    [disable_timesheet_generation]               BIT             NULL,
    [sponsor_email_deprecated]                   NVARCHAR (250)  NULL,
    [rhir_training_date_deprecated]              DATE            NULL,
    [rhir_training_status_id_deprecated]         BIGINT          NULL,
    [pg_pos_training_status_id_deprecated]       BIGINT          NULL,
    [role]                                       NVARCHAR (4000) NULL,
    [pg_pos_training_expire_date_deprecated]     DATE            NULL,
    [auto_approval_time_off_ind]                 BIT             NULL,
    [create_ip_ind]                              BIT             NULL,
    [primary_competency_id]                      BIGINT          NULL,
    [technical_account_ind]                      BIT             NULL,
    [active_ind]                                 BIT             NULL,
    [functional_manager_id]                      BIGINT          NULL,
    [location_id]                                BIGINT          NULL,
    [allow_photo_usage_ind]                      BIT             NULL,
    [allow_fm_approve_timesheet_ind]             BIT             NULL,
    [allow_fm_approve_time_off]                  BIT             NULL,
    [allow_fm_grant_overtime_perm]               BIT             NULL,
    [leave_ind]                                  BIT             NULL,
    [ad_object_id]                               NVARCHAR (100)  NULL,
    [allow_applying_ooo_ind]                     BIT             NULL,
    [az_ad_object_id]                            NVARCHAR (100)  NULL,
    [country_id]                                 BIGINT          NULL,
    [city_id]                                    BIGINT          NULL,
    [country_work_location_id]                   BIGINT          NULL,
    [allow_displaying_holidays_ind]              BIT             NULL,
    [created_by]                                 BIGINT          NULL,
    [modified_by]                                BIGINT          NULL,
    [modified_at]                                DATETIME2 (7)   NULL,
    [creation_at]                                DATETIME2 (7)   NULL,
    [management_community_member_ind]            BIT             NULL,
    [team_owner_ind]                             BIT             NULL,
    [team_leader_ind]                            BIT             NULL,
    [az_ad_account_enabled_ind]                  BIT             NULL,
    [personal_leave_per_year]                    INT             NULL,
    [skills_reviewed_at]                         DATETIME2 (7)   NULL,
    [competency_role_id]                         BIGINT          NULL,
    [leaver_ind_modified_at]                     DATETIME2 (7)   NULL,
    [billable_ind]                               BIT             NULL,
    [total_work_experience]                      INT             NULL,
    [project_manager_ind]                        BIT             NULL,
    [service_level_manager_ind]                  BIT             NULL,
    [seniority_id]                               BIGINT          NULL,
    [skills_reviewed_ind]                        BIT             NULL,
    [leaver_notice_date]                         DATE            NULL,
    [leaver_reason_id]                           BIGINT          NULL,
    [long_term_leave_ind]                        BIT             NULL,
    [long_term_leave_modified_at]                DATETIME2 (7)   NULL,
    [long_term_leave_start_date]                 DATE            NULL,
    [long_term_leave_end_date]                   DATE            NULL,
    [leaver_last_day_of_work]                    DATE            NULL,
    [managerial_requirements_profile_id]         BIGINT          NULL,
    [new_hire_ind]                               BIT             NULL,
    [external_ind]                               BIT             NULL,
    [external_type_id]                           BIGINT          NULL,
    [gallup_assessment_ind]                      BIT             NULL,
    [shift_time_id]                              BIGINT          NULL,
    [resource_row_id]                            BIGINT          NULL,
    [draft_profile_ind]                          BIT             NULL,
    [allow_team_leader_reporters_ooo_events_ind] BIT             NULL,
    [allow_team_owner_reporters_ooo_events_ind]  BIT             NULL,
    [key_talent_program_alumnus_ind]             BIT             NULL,
    [first_day_of_work]                          DATE            NULL
);
GO

