CREATE TABLE [data_mis_project].[fc_revenue_history] (
    [proj_id]                      BIGINT         NULL,
    [proj_name]                    NVARCHAR (MAX) NULL,
    [lingaro_billing_entity]       NVARCHAR (MAX) NULL,
    [project team]                 NVARCHAR (MAX) NULL,
    [po_id]                        BIGINT         NULL,
    [po_number]                    NVARCHAR (MAX) NULL,
    [po_name]                      NVARCHAR (MAX) NULL,
    [billg_mlstn_id]               BIGINT         NULL,
    [parent_clen_name]             NVARCHAR (MAX) NULL,
    [clen_name]                    NVARCHAR (MAX) NULL,
    [billg_mlstn_name]             NVARCHAR (MAX) NULL,
    [billg_mlstn_date]             DATETIME2 (0)  NULL,
    [invc_code]                    NVARCHAR (MAX) NULL,
    [invc_issue_date]              DATETIME2 (0)  NULL,
    [postn_net_bef_disc_amt]       FLOAT (53)     NULL,
    [add_disc]                     FLOAT (53)     NULL,
    [postn_net_disc_amt]           FLOAT (53)     NULL,
    [postn_net_after_disc_amt]     FLOAT (53)     NULL,
    [billg_mlstn_bef_disc_amt]     FLOAT (53)     NULL,
    [billg_mlstn_after_disc_amt]   FLOAT (53)     NULL,
    [po_crncy_code]                NVARCHAR (MAX) NULL,
    [proj_status]                  NVARCHAR (MAX) NULL,
    [billable]                     NVARCHAR (MAX) NULL,
    [reinvoice]                    NVARCHAR (MAX) NULL,
    [invc_dlvry_date]              DATETIME2 (0)  NULL,
    [dlvry_date]                   DATETIME2 (0)  NULL,
    [invc_cmmnt]                   NVARCHAR (MAX) NULL,
    [billg_mlstn_cmmnt]            NVARCHAR (MAX) NULL,
    [project type]                 NVARCHAR (MAX) NULL,
    [additional fund]              NVARCHAR (MAX) NULL,
    [bill_to]                      NVARCHAR (MAX) NULL,
    [pymt_terms]                   NVARCHAR (MAX) NULL,
    [cntry_name]                   NVARCHAR (MAX) NULL,
    [invc dlvr date. dlvr date]    DATETIME2 (0)  NULL,
    [revenue category]             NVARCHAR (MAX) NULL,
    [pln amount]                   FLOAT (53)     NULL,
    [pln discount]                 FLOAT (53)     NULL,
    [pln revenue]                  FLOAT (53)     NULL,
    [pln amount fx rates]          FLOAT (53)     NULL,
    [pln discount fx rates]        FLOAT (53)     NULL,
    [pln revenue  fx rates]        FLOAT (53)     NULL,
    [month]                        DATETIME2 (0)  NULL,
    [disc_check]                   FLOAT (53)     NULL,
    [sub-division]                 NVARCHAR (MAX) NULL,
    [division]                     NVARCHAR (MAX) NULL,
    [department]                   NVARCHAR (MAX) NULL,
    [organization]                 NVARCHAR (MAX) NULL,
    [legal entity]                 NVARCHAR (MAX) NULL,
    [rate]                         FLOAT (53)     NULL,
    [fx rate]                      FLOAT (53)     NULL,
    [project status]               NVARCHAR (MAX) NULL,
    [revenue in original currency] FLOAT (53)     NULL
);
GO

GRANT SELECT
    ON OBJECT::[data_mis_project].[fc_revenue_history] TO [Controling_data_read]
    AS [dbo];
GO

