CREATE TABLE [data_mis_project].[forecast_report_history] (
    [project_id]                     BIGINT          NULL,
    [project_name]                   NVARCHAR (1000) NULL,
    [parent_project_name]            NVARCHAR (1000) NULL,
    [ultimate_parent_name]           NVARCHAR (100)  NULL,
    [ultimate_parent_name_with_rank] NVARCHAR (133)  NULL,
    [client_id]                      BIGINT          NULL,
    [client_name]                    NVARCHAR (300)  NULL,
    [start_date]                     DATE            NULL,
    [end_date]                       DATE            NULL,
    [proj_manager_id]                BIGINT          NULL,
    [proj_manager_name]              NVARCHAR (201)  NULL,
    [project_bu_name]                NVARCHAR (100)  NULL,
    [project_sub_bu_name]            NVARCHAR (100)  NULL,
    [project_delivery_team_name]     NVARCHAR (100)  NULL,
    [project_team_name]              NVARCHAR (100)  NULL,
    [invoicing_code]                 NVARCHAR (10)   NULL,
    [project_billable_ind]           BIT             NULL,
    [investment_ind]                 BIT             NULL,
    [governance_ind]                 BIT             NULL,
    [BM_NCNTRCTD_IND]                BIT             NULL,
    [BM_CNTRCTD_OM_IND]              BIT             NULL,
    [employee_id]                    BIGINT          NULL,
    [booking_status]                 NVARCHAR (20)   NULL,
    [employee_or_avatar]             VARCHAR (8)     NULL,
    [competency_name]                NVARCHAR (100)  NULL,
    [role_name]                      NVARCHAR (100)  NULL,
    [position]                       NVARCHAR (150)  NULL,
    [active_ind]                     BIT             NULL,
    [emp_bu_name]                    NVARCHAR (100)  NULL,
    [emp_sub_bu_name]                NVARCHAR (100)  NULL,
    [emp_senior_delivery_team_name]  NVARCHAR (100)  NULL,
    [delivery_team_name]             NVARCHAR (100)  NULL,
    [country]                        NVARCHAR (200)  NULL,
    [status_code]                    NVARCHAR (100)  NULL,
    [organization_unit_id]           BIGINT          NULL,
    [type]                           NVARCHAR (100)  NULL,
    [start_in_2025_and_not_core]     INT             NOT NULL,
    [sell_and_bill_split]            VARCHAR (26)    NOT NULL,
    [year_month]                     NVARCHAR (4000) NULL,
    [day_date]                       DATETIME2 (0)   NULL,
    [category]                       NVARCHAR (128)  NULL,
    [currency]                       NVARCHAR (MAX)  NULL,
    [value_pln]                      FLOAT (53)      NULL,
    [original_value]                 FLOAT (53)      NULL,
    [value_usd]                      FLOAT (53)      NULL,
    [data_type]                      NVARCHAR (128)  NULL,
    [copy_date]                      DATETIME2 (0)   NULL,
    [is_core]                        NVARCHAR (100)  NULL,
    [status_Label]                   VARCHAR (12)    NULL
);
GO

