CREATE TABLE [data_in].[fin_billing_sheet_vw] (
    [client_name]                             NVARCHAR (300)  NULL,
    [parent_project_name]                     NVARCHAR (1000) NULL,
    [parent_project_manager_name]             NVARCHAR (201)  NULL,
    [project_name]                            NVARCHAR (1000) NULL,
    [project_id]                              BIGINT          NULL,
    [billing_milestone_id]                    BIGINT          NULL,
    [billing_milestone_name]                  NVARCHAR (500)  NULL,
    [billing_milestone_billing_date]          DATE            NULL,
    [billing_milestone_delivery_date]         DATE            NULL,
    [client_po_code]                          NVARCHAR (30)   NULL,
    [po_name]                                 NVARCHAR (200)  NULL,
    [po_modified_at]                          DATETIME2 (7)   NULL,
    [bill_to]                                 NVARCHAR (100)  NULL,
    [country_name]                            NVARCHAR (300)  NULL,
    [invoice_code]                            NVARCHAR (20)   NULL,
    [invoice_delivery_date]                   DATE            NULL,
    [invoice_issue_date]                      DATE            NULL,
    [invoice_due_date]                        DATE            NULL,
    [invoice_arrival_date]                    DATE            NULL,
    [invoice_comment]                         NVARCHAR (500)  NULL,
    [position_net_amount_before_discount]     DECIMAL (19, 2) NULL,
    [invoice_gross_amount]                    DECIMAL (38, 2) NULL,
    [invoice_gross_pln_amount]                DECIMAL (38, 2) NULL,
    [position_gross_amount]                   DECIMAL (19, 2) NULL,
    [position_gross_pln_amount]               DECIMAL (38, 6) NULL,
    [billng_milestone_amount_before_discount] DECIMAL (19, 2) NULL,
    [po_currency_code]                        NVARCHAR (3)    NULL,
    [invoice_amount]                          DECIMAL (38, 2) NULL,
    [active_code]                             VARCHAR (11)    NULL,
    [overdue_payment_ind]                     BIT             NULL,
    [billing_milestone_to_be_billed]          BIT             NULL,
    [wont_be_billed_ind]                      BIT             NULL,
    [po_id]                                   BIGINT          NULL,
    [po_available_amount]                     DECIMAL (19, 2) NULL,
    [billing_milestone_amount_to_invoice]     DECIMAL (38, 6) NULL,
    [can_be_billed_ind]                       BIT             NULL,
    [billing_milestone_comment]               NVARCHAR (4000) NULL,
    [project_billable_ind]                    BIT             NULL,
    [sum_bm]                                  DECIMAL (38, 6) NULL,
    [is_po_sft]                               INT             NULL,
    [current_org_unit_id]                     BIGINT          NULL,
    [current_bu_id]                           BIGINT          NULL,
    [current_sub_bu_id]                       BIGINT          NULL,
    [current_senior_delivery_team_id]         BIGINT          NULL,
    [current_delivery_team_id]                BIGINT          NULL,
    [current_team_id]                         BIGINT          NULL,
    [billng_milestone_amount_after_discount]  DECIMAL (38, 6) NULL,
    [billing_milestone_additional_discount]   DECIMAL (19, 2) NULL,
    [position_net_amount_after_discount]      DECIMAL (20, 2) NULL,
    [position_net_amount_discount]            DECIMAL (19, 2) NULL,
    [billing_milestone_core_discount]         DECIMAL (38, 6) NULL,
    [reinvoice_ind]                           BIT             NULL,
    [billing_milestone_currency_code]         NVARCHAR (3)    NULL,
    [group_po_ind]                            BIT             NULL,
    [change_request_ind]                      BIT             NULL,
    [discount_percentage]                     DECIMAL (19, 2) NULL,
    [legal_entity_name]                       NVARCHAR (100)  NULL
);
GO

