CREATE TABLE [data_in].[fin_invoice_position_vw] (
    [invoice_id]                          BIGINT          NULL,
    [invoice_code]                        NVARCHAR (20)   NULL,
    [invoice_comment]                     NVARCHAR (500)  NULL,
    [delivery_date]                       DATE            NULL,
    [delivery_month_name]                 NVARCHAR (4000) NULL,
    [issue_date]                          DATE            NULL,
    [due_date]                            DATE            NULL,
    [invoice_arrival_date]                DATE            NULL,
    [payment_id]                          BIGINT          NULL,
    [payment_amount]                      DECIMAL (19, 2) NULL,
    [payment_modified_at]                 DATETIME2 (7)   NULL,
    [invoice_amount]                      DECIMAL (38, 2) NULL,
    [invoice_gross_amount]                DECIMAL (38, 2) NULL,
    [position_id]                         BIGINT          NULL,
    [position_name]                       NVARCHAR (4000) NULL,
    [position_net_amount_before_discount] DECIMAL (19, 2) NULL,
    [position_gross_amount]               DECIMAL (19, 2) NULL,
    [custom_gross_amount_ind]             BIT             NULL,
    [position_net_amount_discount]        DECIMAL (19, 2) NULL,
    [position_net_amount_after_discount]  DECIMAL (20, 2) NULL,
    [position_pln_amount]                 DECIMAL (38, 6) NULL,
    [position_gross_pln_amount]           DECIMAL (38, 6) NULL,
    [billing_milestone_id]                BIGINT          NULL,
    [invoice_exchange_rate]               DECIMAL (19, 4) NULL,
    [invoice_currency_code]               NVARCHAR (3)    NULL,
    [invoice_pln_amount]                  DECIMAL (38, 2) NULL,
    [invoice_gross_pln_amount]            DECIMAL (38, 2) NULL,
    [project_name]                        NVARCHAR (1000) NULL,
    [project_id]                          BIGINT          NULL
);
GO

