CREATE TABLE [data_in].[fin_project_cost_vw] (
    [id]                                  BIGINT          NULL,
    [project_id]                          BIGINT          NULL,
    [project_name]                        NVARCHAR (1000) NULL,
    [parent_project_name]                 NVARCHAR (1000) NULL,
    [employee_id]                         BIGINT          NULL,
    [employee_name]                       NVARCHAR (201)  NULL,
    [additional_cost_description]         NVARCHAR (500)  NULL,
    [day_date]                            DATE            NULL,
    [month_name]                          NVARCHAR (4000) NULL,
    [timesheet_code]                      NVARCHAR (2000) NULL,
    [timesheet_code_name]                 NVARCHAR (1000) NULL,
    [employee_rate_amount]                DECIMAL (12, 2) NULL,
    [employee_rate_currency_code]         NVARCHAR (3)    NULL,
    [client_employee_rate_amount]         DECIMAL (12, 2) NULL,
    [client_employee_rate_currency_code]  NVARCHAR (3)    NULL,
    [project_employee_rate_amount]        DECIMAL (12, 2) NULL,
    [project_employee_rate_currency_code] NVARCHAR (3)    NULL,
    [final_rate_amount]                   DECIMAL (12, 2) NULL,
    [exchange_rate]                       DECIMAL (19, 4) NULL,
    [time_minutes]                        DECIMAL (27, 8) NULL,
    [time_days]                           DECIMAL (27, 8) NULL,
    [multiplier]                          DECIMAL (13, 3) NULL,
    [final_rate_currency_code]            NVARCHAR (3)    NULL,
    [project_cost_type_code]              VARCHAR (10)    NULL,
    [cost_type_code]                      NVARCHAR (10)   NULL,
    [final_cost_pln_amount]               DECIMAL (38, 6) NULL,
    [final_cost_amount]                   DECIMAL (38, 5) NULL,
    [final_ind]                           BIT             NULL,
    [non_billable_ind]                    BIT             NULL,
    [time_comment]                        NVARCHAR (4000) NULL,
    [current_organization_unit_id]        BIGINT          NULL,
    [current_business_unit_id]            BIGINT          NULL,
    [current_sub_business_unit_id]        BIGINT          NULL,
    [current_senior_delivery_team_id]     BIGINT          NULL,
    [current_delivery_team_id]            BIGINT          NULL,
    [current_team_id]                     BIGINT          NULL,
    [stand_by]                            BIT             NULL,
    [timsheet_status_code]                NVARCHAR (100)  NULL,
    [timesheet_start_date]                DATE            NULL,
    [standard_employee_rate_amount]       DECIMAL (12, 2) NULL,
    [standard_final_cost_amount]          DECIMAL (38, 6) NULL,
    [standard_final_cost_pln_amount]      DECIMAL (38, 6) NULL
);
GO

