CREATE TABLE [data_in].[fin_actuals_vw] (
    [id]                                  BIGINT          NULL,
    [project_id]                          BIGINT          NULL,
    [project_name]                        NVARCHAR (1000) NULL,
    [parent_project_name]                 NVARCHAR (1000) NULL,
    [employee_id]                         BIGINT          NULL,
    [empee_name]                          NVARCHAR (201)  NULL,
    [day_date]                            DATE            NULL,
    [month_name]                          NVARCHAR (4000) NULL,
    [timesheet_code]                      NVARCHAR (2000) NULL,
    [timesheet_code_name]                 NVARCHAR (1000) NULL,
    [stand_by]                            BIT             NULL,
    [non_billable_ind]                    BIT             NULL,
    [time_comment]                        NVARCHAR (4000) NULL,
    [final_ind]                           BIT             NULL,
    [employee_rate_amount]                DECIMAL (12, 2) NULL,
    [employee_rate_currency_code]         NVARCHAR (3)    NULL,
    [client_employee_rate_amount]         DECIMAL (12, 2) NULL,
    [client_employee_rate_currency_code]  NVARCHAR (3)    NULL,
    [project_employee_rate_amount]        DECIMAL (12, 2) NULL,
    [project_employee_rate_currency_code] NVARCHAR (3)    NULL,
    [final_rate_amount]                   DECIMAL (12, 2) NULL,
    [exchange_rate]                       DECIMAL (19, 4) NULL,
    [time_minutes]                        BIGINT          NULL,
    [time_days]                           FLOAT (53)      NULL,
    [multiplier]                          DECIMAL (6, 3)  NULL,
    [final_rate_currency_code]            NVARCHAR (3)    NULL,
    [final_cost_pln_amount]               FLOAT (53)      NULL,
    [final_cost_amount]                   FLOAT (53)      NULL,
    [timesheet_id]                        BIGINT          NULL,
    [timesheet_version_id]                BIGINT          NULL,
    [ip_code]                             BIT             NULL,
    [standard_employee_rate_amount]       DECIMAL (12, 2) NULL,
    [standard_final_cost_amount]          FLOAT (53)      NULL,
    [standard_final_cost_pln_amt]         FLOAT (53)      NULL,
    [final_client_rate_card_id]           BIGINT          NULL,
    [final_client_rate_card_name]         NVARCHAR (200)  NULL,
    [final_rate_id]                       BIGINT          NULL,
    [final_rate_country_id]               BIGINT          NULL,
    [final_rate_role_name]                NVARCHAR (200)  NULL,
    [final_rate_seniority]                NVARCHAR (100)  NULL,
    [final_rate_external_role_id]         NVARCHAR (100)  NULL,
    [standard_final_cost_rate_card_id]    BIGINT          NULL,
    [standard_final_cost_rate_card_name]  NVARCHAR (200)  NULL,
    [standard_final_cost_rate_id]         BIGINT          NULL,
    [standard_final_cost_country_id]      BIGINT          NULL,
    [standard_final_cost_role_name]       NVARCHAR (100)  NULL,
    [standard_final_cost_seniority_name]  NVARCHAR (200)  NULL
);
GO

