CREATE TABLE [data_in].[org_unit_flatten] (
    [id]                             BIGINT          NULL,
    [name]                           NVARCHAR (100)  NULL,
    [parent_id]                      BIGINT          NULL,
    [unit_level]                     INT             NULL,
    [type]                           NVARCHAR (3)    NULL,
    [leader_id]                      BIGINT          NULL,
    [area]                           NVARCHAR (1000) NULL,
    [team_id]                        BIGINT          NULL,
    [team_name]                      NVARCHAR (100)  NULL,
    [parnt_team_id]                  BIGINT          NULL,
    [team_lvl]                       INT             NULL,
    [team_type]                      NVARCHAR (3)    NULL,
    [team_leader_id]                 BIGINT          NULL,
    [team_area]                      NVARCHAR (1000) NULL,
    [delivery_team_id]               BIGINT          NULL,
    [delivery_team_name]             NVARCHAR (100)  NULL,
    [parnt_delivery_team_id]         BIGINT          NULL,
    [delivery_team_lvl]              INT             NULL,
    [delivery_team_type]             NVARCHAR (3)    NULL,
    [delivery_team_leader_id]        BIGINT          NULL,
    [delivery_team_area]             NVARCHAR (1000) NULL,
    [senior_delivery_team_id]        BIGINT          NULL,
    [senior_delivery_team_name]      NVARCHAR (100)  NULL,
    [parnt_senior_delivery_team_id]  BIGINT          NULL,
    [senior_delivery_team_lvl]       INT             NULL,
    [senior_delivery_team_type]      NVARCHAR (3)    NULL,
    [senior_delivery_team_leader_id] BIGINT          NULL,
    [senior_delivery_team_area]      NVARCHAR (1000) NULL,
    [sub_bu_id]                      BIGINT          NULL,
    [sub_bu_name]                    NVARCHAR (100)  NULL,
    [sub_parnt_bu_id]                BIGINT          NULL,
    [sub_bu_lvl]                     INT             NULL,
    [sub_bu_type]                    NVARCHAR (3)    NULL,
    [sub_bu_leader_id]               BIGINT          NULL,
    [sub_bu_area]                    NVARCHAR (1000) NULL,
    [bu_id]                          BIGINT          NULL,
    [bu_name]                        NVARCHAR (100)  NULL,
    [parnt_bu_id]                    BIGINT          NULL,
    [bu_lvl]                         INT             NULL,
    [bu_type]                        NVARCHAR (3)    NULL,
    [bu_leader_id]                   BIGINT          NULL,
    [bu_area]                        NVARCHAR (1000) NULL
);
GO

