CREATE TABLE [data_in].[proj_resource_row_vw] (
    [id]                          BIGINT          NULL,
    [name]                        NVARCHAR (200)  NULL,
    [source]                      NVARCHAR (100)  NULL,
    [version_number]              INT             NULL,
    [project_id]                  BIGINT          NULL,
    [project_name]                NVARCHAR (1000) NULL,
    [client_id]                   BIGINT          NULL,
    [client_name]                 NVARCHAR (300)  NULL,
    [owner_id]                    BIGINT          NULL,
    [owner_name]                  NVARCHAR (201)  NULL,
    [cc_owner_id]                 BIGINT          NULL,
    [cc_owner_name]               NVARCHAR (201)  NULL,
    [competency_id]               BIGINT          NULL,
    [competency_name]             NVARCHAR (100)  NULL,
    [role_id]                     BIGINT          NULL,
    [role_name]                   NVARCHAR (100)  NULL,
    [seniority_id]                BIGINT          NULL,
    [seniority_name]              NVARCHAR (200)  NULL,
    [start_date]                  DATE            NULL,
    [end_date]                    DATE            NULL,
    [country_id]                  BIGINT          NULL,
    [country_name]                NVARCHAR (200)  NULL,
    [country_code]                NVARCHAR (2)    NULL,
    [status]                      NVARCHAR (100)  NULL,
    [comment]                     NVARCHAR (4000) NULL,
    [on_hold_ind]                 BIT             NULL,
    [creation_at]                 DATETIME2 (7)   NULL,
    [modified_at]                 DATETIME2 (7)   NULL,
    [created_by]                  BIGINT          NULL,
    [created_by_employee]         NVARCHAR (201)  NULL,
    [modified_by]                 BIGINT          NULL,
    [modified_by_employee]        NVARCHAR (201)  NULL,
    [any_location_ind]            BIT             NULL,
    [demand_type]                 NVARCHAR (100)  NULL,
    [hiring_id]                   NVARCHAR (100)  NULL,
    [starting_required_capacity]  DECIMAL (12, 4) NULL,
    [proposed_talent]             NVARCHAR (4000) NULL,
    [invoicing_code]              NVARCHAR (10)   NULL,
    [project_cost_category]       VARCHAR (10)    NULL,
    [role_aspect_id]              BIGINT          NULL,
    [role_aspect_name]            NVARCHAR (200)  NULL,
    [notes]                       NVARCHAR (MAX)  NULL,
    [original_start_date]         DATE            NULL,
    [previous_owner_id]           BIGINT          NULL,
    [previous_owner_name]         NVARCHAR (201)  NULL,
    [ultimate_parent_client_id]   BIGINT          NULL,
    [ultimate_parent_client_name] NVARCHAR (300)  NULL,
    [time_zone_id]                BIGINT          NULL,
    [time_zone_name]              NVARCHAR (100)  NULL
);
GO

