CREATE TABLE [data_in].[proj] (
    [project_id]                               BIGINT          NULL,
    [parent_project_id]                        BIGINT          NULL,
    [parent_project_ind]                       BIT             NULL,
    [manager_id]                               BIGINT          NULL,
    [client_id]                                BIGINT          NULL,
    [time_off_ind]                             BIT             NULL,
    [project_billable_ind]                     BIT             NULL,
    [code]                                     NVARCHAR (100)  NULL,
    [name]                                     NVARCHAR (1000) NULL,
    [start_date]                               DATE            NULL,
    [end_date]                                 DATE            NULL,
    [change_date]                              DATE            NULL,
    [status_code]                              NVARCHAR (100)  NULL,
    [client_rate_card_id]                      BIGINT          NULL,
    [invoicing_code]                           NVARCHAR (10)   NULL,
    [change_by]                                BIGINT          NULL,
    [project_invoicing_info_old]               NVARCHAR (4000) NULL,
    [overtime_compensation_ind]                BIT             NULL,
    [holiday_ind]                              BIT             NULL,
    [obs_client_project_manager_name_old]      NVARCHAR (100)  NULL,
    [sick_leave_ind]                           BIT             NULL,
    [personal_leave_ind]                       BIT             NULL,
    [other_time_off_ind]                       BIT             NULL,
    [share_point_link]                         NVARCHAR (4000) NULL,
    [bm_confirmation_alert_ind]                BIT             NULL,
    [svn_link]                                 NVARCHAR (1000) NULL,
    [engagement_type_id]                       BIGINT          NULL,
    [management_tool_id]                       BIGINT          NULL,
    [obs_client_project_manager_mail_old]      NVARCHAR (100)  NULL,
    [wiki_link]                                NVARCHAR (2000) NULL,
    [default_currency]                         NVARCHAR (3)    NULL,
    [description]                              NVARCHAR (500)  NULL,
    [governance_ind]                           BIT             NULL,
    [investment_ind]                           BIT             NULL,
    [information_classification_code]          NVARCHAR (100)  NULL,
    [cheetah_project_ind]                      BIT             NULL,
    [client_contact_id]                        BIGINT          NULL,
    [creation_date]                            DATE            NULL,
    [engagement_scope]                         NVARCHAR (4000) NULL,
    [assumptions_constraints]                  NVARCHAR (4000) NULL,
    [high_level_risks]                         NVARCHAR (4000) NULL,
    [engagement_rules]                         NVARCHAR (4000) NULL,
    [department_id]                            BIGINT          NULL,
    [share_point_auto_link]                    NVARCHAR (4000) NULL,
    [region_id]                                BIGINT          NULL,
    [share_point_status_code]                  NVARCHAR (40)   NULL,
    [is_status_required]                       BIT             NULL,
    [share_point_group_name]                   NVARCHAR (200)  NULL,
    [share_point_account_name]                 NVARCHAR (200)  NULL,
    [service_area_id]                          BIGINT          NULL,
    [business_unit_id_deprecated]              BIGINT          NULL,
    [it_client_project_manager_id]             BIGINT          NULL,
    [business_client_project_manager_id]       BIGINT          NULL,
    [new_cheetah_ind]                          BIT             NULL,
    [double_counting_ind]                      BIT             NULL,
    [new_sales_ind]                            BIT             NULL,
    [cloud_project_ind]                        BIT             NULL,
    [sow_sign_date]                            DATE            NULL,
    [coupa_number]                             BIGINT          NULL,
    [coupa_cr_number]                          BIGINT          NULL,
    [parent_financial_project_id]              BIGINT          NULL,
    [pg_band_three_id_deprecated]              BIGINT          NULL,
    [security_leader_id]                       BIGINT          NULL,
    [sales_force_opportunity_id]               NVARCHAR (100)  NULL,
    [jira_tenant_id]                           BIGINT          NULL,
    [jira_integration_ind]                     BIT             NULL,
    [first_end_date]                           DATE            NULL,
    [project_scale]                            BIGINT          NULL,
    [project_risk]                             BIGINT          NULL,
    [business_criticality]                     BIGINT          NULL,
    [project_priority]                         BIGINT          NULL,
    [development_by_lingaro_ind]               BIT             NULL,
    [technical_leader_id]                      BIGINT          NULL,
    [sonar_link]                               NVARCHAR (1000) NULL,
    [revenue_type]                             NVARCHAR (100)  NULL,
    [share_point_status_link]                  NVARCHAR (4000) NULL,
    [share_point_group_id]                     NVARCHAR (100)  NULL,
    [share_point_error_message]                NVARCHAR (4000) NULL,
    [parent_dc_project_id]                     BIGINT          NULL,
    [manual_revenue_recognition_ind]           BIT             NULL,
    [internal_code_repository]                 NVARCHAR (4000) NULL,
    [work_category_id]                         BIGINT          NULL,
    [agile_framework_id]                       BIGINT          NULL,
    [agile_score]                              BIGINT          NULL,
    [program_id]                               BIGINT          NULL,
    [is_health_check_required]                 BIT             NULL,
    [creation_at]                              DATETIME2 (7)   NULL,
    [modified_at]                              DATETIME2 (7)   NULL,
    [created_by]                               BIGINT          NULL,
    [modified_by]                              BIGINT          NULL,
    [health_check_url]                         NVARCHAR (4000) NULL,
    [sharepoint_attempt_count]                 INT             NULL,
    [engagement_manager_id]                    BIGINT          NULL,
    [predecessor_id]                           BIGINT          NULL,
    [first_start_date]                         DATE            NULL,
    [project_id_used_for_share_point_creation] BIGINT          NULL,
    [project_closure_document_url]             NVARCHAR (4000) NULL,
    [project_closure_document_url_updated_by]  BIGINT          NULL,
    [revenue_recognition_ind]                  BIT             NULL
);
GO

