CREATE TABLE [data_in].[proj_status_report] (
    [id]                                    BIGINT          NULL,
    [project_id]                            BIGINT          NULL,
    [status_day_date]                       DATE            NULL,
    [overall_health_status]                 NVARCHAR (100)  NULL,
    [cost_status]                           NVARCHAR (100)  NULL,
    [cost_status_visibility]                NVARCHAR (100)  NULL,
    [time_status]                           NVARCHAR (100)  NULL,
    [time_status_visibility]                NVARCHAR (100)  NULL,
    [scope_status]                          NVARCHAR (100)  NULL,
    [scope_status_visibility]               NVARCHAR (100)  NULL,
    [resource_status]                       NVARCHAR (100)  NULL,
    [resource_status_visibility]            NVARCHAR (100)  NULL,
    [full_link]                             NVARCHAR (500)  NULL,
    [project_finance_current]               DECIMAL (19, 4) NULL,
    [project_finance_forecast]              DECIMAL (19, 4) NULL,
    [project_finance_currency]              NVARCHAR (3)    NULL,
    [automatic_generated_report_ind]        BIT             NULL,
    [executive_summary]                     NVARCHAR (MAX)  NULL,
    [help_needed]                           NVARCHAR (MAX)  NULL,
    [help_needed_lingaro]                   NVARCHAR (MAX)  NULL,
    [activities_planned_next_week]          NVARCHAR (MAX)  NULL,
    [completed_activities_past_week]        NVARCHAR (MAX)  NULL,
    [identified_risk]                       NVARCHAR (MAX)  NULL,
    [current_ind]                           BIT             NULL,
    [project_manager_id_in_creation_moment] BIGINT          NULL,
    [created_by]                            BIGINT          NULL,
    [modified_by]                           BIGINT          NULL,
    [creation_at]                           DATETIME2 (7)   NULL,
    [modified_at]                           DATETIME2 (7)   NULL
);
GO

