CREATE TABLE [data_in].[proj_all_type_client] (
    [id]                                 BIGINT          NULL,
    [name]                               NVARCHAR (300)  NULL,
    [share_point_name]                   NVARCHAR (300)  NULL,
    [leave_contact_email]                NVARCHAR (200)  NULL,
    [leave_notification_period_days]     INT             NULL,
    [active_notification_ind]            BIT             NULL,
    [account_manager_id]                 BIGINT          NULL,
    [created_by]                         BIGINT          NULL,
    [modified_by]                        BIGINT          NULL,
    [modified_at]                        DATETIME2 (7)   NULL,
    [creation_at]                        DATETIME2 (7)   NULL,
    [salesforce_id]                      NVARCHAR (100)  NULL,
    [ultimate_parent_id]                 NVARCHAR (100)  NULL,
    [ultimate_parent_name]               NVARCHAR (100)  NULL,
    [emergency_contact]                  NVARCHAR (2000) NULL,
    [last_verified_at]                   DATETIME2 (7)   NULL,
    [last_verified_by]                   BIGINT          NULL,
    [share_point_group_id]               NVARCHAR (2000) NULL,
    [share_point_url]                    NVARCHAR (2000) NULL,
    [delivery_owner_id]                  BIGINT          NULL,
    [emergency_contact_excluded_ind]     BIT             NULL,
    [emergency_contact_exclusion_reason] NVARCHAR (1000) NULL,
    [emergency_contact_modified_at]      DATETIME2 (7)   NULL,
    [emergency_contact_modified_by]      BIGINT          NULL,
    [industry]                           NVARCHAR (200)  NULL,
    [industry_group]                     NVARCHAR (200)  NULL,
    [industry_description]               NVARCHAR (1000) NULL,
    [stars_segmentation]                 NVARCHAR (200)  NULL,
    [type]                               NVARCHAR (100)  NULL
);
GO

