CREATE TABLE [data_in].[proj_account_assignment_vw] (
    [id]                             BIGINT          NULL,
    [employee_id]                    BIGINT          NULL,
    [employee_name]                  NVARCHAR (201)  NULL,
    [adm_account_assignment_request] DECIMAL (6, 3)  NULL,
    [bucket_id]                      BIGINT          NULL,
    [bucket_name]                    NVARCHAR (500)  NULL,
    [start_date]                     DATE            NULL,
    [end_date]                       DATE            NULL,
    [status]                         NVARCHAR (50)   NULL,
    [comment]                        NVARCHAR (1000) NULL,
    [creation_at]                    DATETIME2 (7)   NULL,
    [modified_at]                    DATETIME2 (7)   NULL,
    [created_by]                     BIGINT          NULL,
    [created_by_employee]            NVARCHAR (201)  NULL,
    [modified_by]                    BIGINT          NULL,
    [modified_by_employee]           NVARCHAR (201)  NULL,
    [reviewed_by_lm_ind]             BIT             NULL,
    [reviewed_by_lm_id]              BIGINT          NULL,
    [reviewed_by_line_manager]       NVARCHAR (201)  NULL,
    [review_date_time]               DATETIME2 (7)   NULL,
    [review_comment]                 NVARCHAR (1000) NULL,
    [do_not_extend_ind]              BIT             NULL,
    [adm_requestor_id]               BIGINT          NULL,
    [adm_requestor]                  NVARCHAR (201)  NULL,
    [line_manager_id]                BIGINT          NULL,
    [line_manager]                   NVARCHAR (201)  NULL,
    [approved_by_lm_ind]             BIT             NULL,
    [rejected_by_lm_ind]             BIT             NULL,
    [active_ind]                     BIT             NULL,
    [cc_team_id]                     BIGINT          NULL,
    [cc_team_name]                   NVARCHAR (100)  NULL,
    [employee_role_name]             NVARCHAR (100)  NULL
);
GO

