CREATE TABLE [data_in].[proj_resource_row] (
    [id]                            BIGINT          NULL,
    [project_id]                    BIGINT          NULL,
    [name]                          NVARCHAR (200)  NULL,
    [version_number]                INT             NULL,
    [source]                        NVARCHAR (100)  NULL,
    [status]                        NVARCHAR (100)  NULL,
    [start_date]                    DATE            NULL,
    [end_date]                      DATE            NULL,
    [country_id]                    BIGINT          NULL,
    [competency_id]                 BIGINT          NULL,
    [role_id]                       BIGINT          NULL,
    [seniority_id]                  BIGINT          NULL,
    [owner_id]                      BIGINT          NULL,
    [valuation_version_id]          BIGINT          NULL,
    [total_man_days]                DECIMAL (9, 2)  NULL,
    [competency_role_rate_per_hour] DECIMAL (9, 2)  NULL,
    [total_cost]                    DECIMAL (19, 2) NULL,
    [creation_at]                   DATETIME2 (7)   NULL,
    [modified_at]                   DATETIME2 (7)   NULL,
    [created_by]                    BIGINT          NULL,
    [modified_by]                   BIGINT          NULL,
    [on_hold_ind]                   BIT             NULL,
    [comment]                       NVARCHAR (4000) NULL,
    [cc_owner_id]                   BIGINT          NULL,
    [any_location_ind]              BIT             NULL,
    [valuation_version_row_id]      BIGINT          NULL,
    [demand_type]                   NVARCHAR (100)  NULL,
    [cancel_reason]                 NVARCHAR (2000) NULL,
    [hiring_id]                     NVARCHAR (100)  NULL,
    [recommended_employee_id]       BIGINT          NULL,
    [accepted_at]                   DATETIME2 (7)   NULL,
    [last_clarification_at]         DATETIME2 (7)   NULL,
    [allowed_alternative_date_ind]  BIT             NULL,
    [role_aspect_id]                BIGINT          NULL,
    [original_start_date]           DATE            NULL,
    [previous_owner_id]             BIGINT          NULL,
    [time_zone_id]                  BIGINT          NULL
);
GO

