CREATE TABLE [data_in].[proj_booking] (
    [id]                   BIGINT          NULL,
    [employee_id]          BIGINT          NULL,
    [project_id]           BIGINT          NULL,
    [week_number]          NVARCHAR (10)   NULL,
    [start_date]           DATE            NULL,
    [end_date]             DATE            NULL,
    [booking_percentage]   DECIMAL (12, 4) NULL,
    [booking_man_days]     DECIMAL (12, 4) NULL,
    [booking_hours]        DECIMAL (12, 4) NULL,
    [status]               NVARCHAR (20)   NULL,
    [criticality]          NVARCHAR (20)   NULL,
    [comment]              NVARCHAR (4000) NULL,
    [competency_role_id]   BIGINT          NULL,
    [creation_at]          DATETIME2 (7)   NULL,
    [modified_at]          DATETIME2 (7)   NULL,
    [created_by]           BIGINT          NULL,
    [modified_by]          BIGINT          NULL,
    [competency_id]        BIGINT          NULL,
    [role_id]              BIGINT          NULL,
    [seniority_id]         BIGINT          NULL,
    [working_days_cnt]     INT             NULL,
    [resource_row_id]      BIGINT          NULL,
    [resource_proposal_id] BIGINT          NULL,
    [location_id]          BIGINT          NULL,
    [calendar_id]          BIGINT          NULL,
    [month_name]           NVARCHAR (15)   NULL
);
GO

