CREATE TABLE [data_in].[proj_vw] (
    [project_id]                        BIGINT          NULL,
    [project_group_id]                  BIGINT          NULL,
    [project_group_name]                NVARCHAR (1000) NULL,
    [project_group_ind]                 BIT             NULL,
    [manager_id]                        BIGINT          NULL,
    [manager_name]                      NVARCHAR (201)  NULL,
    [client_id]                         BIGINT          NULL,
    [client_name]                       NVARCHAR (300)  NULL,
    [project_billable_ind]              BIT             NULL,
    [project_code]                      NVARCHAR (100)  NULL,
    [project_name]                      NVARCHAR (1000) NULL,
    [start_date]                        DATE            NULL,
    [end_date]                          DATE            NULL,
    [change_date]                       DATE            NULL,
    [status_code]                       NVARCHAR (100)  NULL,
    [invoicing_code]                    NVARCHAR (10)   NULL,
    [engagement_type_id]                BIGINT          NULL,
    [engagement_type_name]              NVARCHAR (50)   NULL,
    [management_tool_id]                BIGINT          NULL,
    [management_tool_name]              NVARCHAR (50)   NULL,
    [description]                       NVARCHAR (500)  NULL,
    [governance_ind]                    BIT             NULL,
    [investment_ind]                    BIT             NULL,
    [parent_financial_project_id]       BIGINT          NULL,
    [parent_financial_project_name]     NVARCHAR (1000) NULL,
    [parent_fin_proj_ind]               BIT             NULL,
    [project_priority]                  BIGINT          NULL,
    [project_priority_name]             VARCHAR (7)     NULL,
    [project_scale_name]                VARCHAR (7)     NULL,
    [project_risk_name]                 VARCHAR (7)     NULL,
    [project_bussines_criticality_name] VARCHAR (7)     NULL,
    [work_category_id]                  BIGINT          NULL,
    [work_category_name]                NVARCHAR (200)  NULL,
    [bu_id]                             BIGINT          NULL,
    [bu_name]                           NVARCHAR (100)  NULL,
    [sub_bu_id]                         BIGINT          NULL,
    [sub_bu_name]                       NVARCHAR (100)  NULL,
    [delivery_team_id]                  BIGINT          NULL,
    [delivery_team_name]                NVARCHAR (100)  NULL,
    [team_id]                           BIGINT          NULL,
    [team_name]                         NVARCHAR (100)  NULL,
    [organization_unit_id]              BIGINT          NULL,
    [organization_unit_name]            NVARCHAR (100)  NULL,
    [is_status_required]                BIT             NULL,
    [agile_framework_id]                BIGINT          NULL,
    [agile_score]                       BIGINT          NULL,
    [security_ind]                      BIT             NULL,
    [engagement_manager_id]             BIGINT          NULL,
    [engagement_manager_name]           NVARCHAR (201)  NULL,
    [predecessor_id]                    BIGINT          NULL,
    [predecessor_name]                  NVARCHAR (1000) NULL
);
GO

