CREATE TABLE [data_in].[proj_opportunity] (
    [id]                               BIGINT          NULL,
    [salesforce_id]                    NVARCHAR (100)  NULL,
    [name]                             NVARCHAR (200)  NULL,
    [client_id_sf]                     NVARCHAR (100)  NULL,
    [stage]                            NVARCHAR (100)  NULL,
    [work_start_date]                  DATE            NULL,
    [work_duration]                    DECIMAL (18, 2) NULL,
    [close_date]                       DATE            NULL,
    [contract_date]                    DATE            NULL,
    [forecast_category]                NVARCHAR (100)  NULL,
    [fc_probability]                   NVARCHAR (100)  NULL,
    [type]                             NVARCHAR (100)  NULL,
    [order_type]                       NVARCHAR (100)  NULL,
    [work_category]                    NVARCHAR (100)  NULL,
    [competitive]                      NVARCHAR (100)  NULL,
    [sharepoint_link]                  NVARCHAR (1000) NULL,
    [practice_area]                    NVARCHAR (300)  NULL,
    [description]                      NVARCHAR (3000) NULL,
    [next_step]                        NVARCHAR (1000) NULL,
    [leading_business_unit]            NVARCHAR (100)  NULL,
    [leading_sub_business_unit]        NVARCHAR (100)  NULL,
    [delivery_team]                    NVARCHAR (100)  NULL,
    [service_partner]                  NVARCHAR (100)  NULL,
    [po_number]                        NVARCHAR (100)  NULL,
    [revenue_stream_id_sf]             NVARCHAR (100)  NULL,
    [amount]                           DECIMAL (18, 2) NULL,
    [currency_code]                    NVARCHAR (3)    NULL,
    [owner_name]                       NVARCHAR (200)  NULL,
    [owner_mail]                       NVARCHAR (200)  NULL,
    [opportunity_number]               NVARCHAR (100)  NULL,
    [band]                             NVARCHAR (100)  NULL,
    [band_level]                       NVARCHAR (100)  NULL,
    [creation_at]                      DATETIME2 (7)   NULL,
    [modified_at]                      DATETIME2 (7)   NULL,
    [created_by]                       BIGINT          NULL,
    [modified_by]                      BIGINT          NULL,
    [contact_id_sf]                    NVARCHAR (100)  NULL,
    [owner_id_sf]                      NVARCHAR (100)  NULL,
    [owner_id]                         BIGINT          NULL,
    [created_by_sf]                    BIGINT          NULL,
    [creation_date_sf]                 DATETIME2 (7)   NULL,
    [modified_by_sf]                   BIGINT          NULL,
    [last_modification_date_sf]        DATETIME2 (7)   NULL,
    [sow_attached_ind]                 BIT             NULL,
    [pricing_file_attached_ind]        BIT             NULL,
    [reason]                           NVARCHAR (1000) NULL,
    [other_reason]                     NVARCHAR (3000) NULL,
    [leading_technology_partner]       NVARCHAR (200)  NULL,
    [verified_ind]                     BIT             NULL,
    [active_ind]                       BIT             NULL,
    [smaller_strategic]                NVARCHAR (100)  NULL,
    [top_account_big_deal]             NVARCHAR (100)  NULL,
    [new_logo]                         NVARCHAR (100)  NULL,
    [action_required]                  NVARCHAR (100)  NULL,
    [included_in_forecast]             NVARCHAR (100)  NULL,
    [presales_engagement]              NVARCHAR (100)  NULL,
    [presales_engagement_request_time] NVARCHAR (100)  NULL,
    [presales_manager_one]             NVARCHAR (100)  NULL,
    [presales_manager_two]             NVARCHAR (100)  NULL,
    [client_id]                        BIGINT          NULL,
    [work_end_date]                    DATE            NULL
);
GO

