CREATE TABLE [data_in].[proj_booking_daily_vw] (
    [booking_id]                NVARCHAR (4000) NULL,
    [employee_id]               BIGINT          NULL,
    [employee_full_name]        NVARCHAR (201)  NULL,
    [location_id]               BIGINT          NULL,
    [email]                     NVARCHAR (150)  NULL,
    [project_id]                BIGINT          NULL,
    [project_name]              NVARCHAR (1000) NULL,
    [day_date]                  DATE            NULL,
    [month_name]                NVARCHAR (4000) NULL,
    [first_day_of_week]         DATE            NULL,
    [week_number]               VARCHAR (13)    NULL,
    [splitted_week_number]      VARCHAR (15)    NULL,
    [booking_percentage]        DECIMAL (12, 4) NULL,
    [booking_man_days]          DECIMAL (16, 8) NULL,
    [booking_hours]             DECIMAL (18, 8) NULL,
    [week_cnt_in_split]         INT             NULL,
    [month_cnt]                 INT             NULL,
    [status]                    NVARCHAR (20)   NULL,
    [start_date]                DATE            NULL,
    [end_date]                  DATE            NULL,
    [criticality]               NVARCHAR (20)   NULL,
    [time_off_ind]              BIT             NULL,
    [competency_id]             BIGINT          NULL,
    [role_id]                   BIGINT          NULL,
    [seniority_id]              BIGINT          NULL,
    [competency_role_full_name] NVARCHAR (303)  NULL,
    [comment]                   NVARCHAR (4000) NULL
);
GO

