CREATE TABLE [data_in].[valuation_version_row] (
    [id]                                    BIGINT          NOT NULL,
    [valuation_version_id]                  BIGINT          NULL,
    [primary_employee_id]                   BIGINT          NULL,
    [secondary_employee_id]                 BIGINT          NULL,
    [client_rate_card_id]                   BIGINT          NULL,
    [role_id]                               BIGINT          NULL,
    [client_employee_rate_id]               BIGINT          NULL,
    [on_call_hours_per_day]                 BIGINT          NULL,
    [margin]                                DECIMAL (14, 4) NULL,
    [country_id]                            BIGINT          NULL,
    [competency]                            NVARCHAR (1000) NULL,
    [family]                                NVARCHAR (1000) NULL,
    [creation_at]                           DATETIME2 (7)   NULL,
    [modified_at]                           DATETIME2 (7)   NULL,
    [created_by]                            BIGINT          NULL,
    [modified_by]                           BIGINT          NULL,
    [comment]                               NVARCHAR (4000) NULL,
    [total_man_days]                        DECIMAL (9, 2)  NULL,
    [cost_type]                             NVARCHAR (1000) NULL,
    [client_rate_per_hour]                  DECIMAL (9, 2)  NULL,
    [cross_charge_per_hour]                 DECIMAL (9, 2)  NULL,
    [value_based_on_rate_card]              DECIMAL (19, 2) NULL,
    [total_cost]                            DECIMAL (19, 2) NULL,
    [competency_id]                         BIGINT          NULL,
    [seniority_id]                          BIGINT          NULL,
    [any_location_ind]                      BIT             NULL,
    [financials_modification_date]          DATETIME2 (7)   NULL,
    [custom_discount_percentage]            DECIMAL (9, 2)  NULL,
    [custom_client_rate_per_hour]           DECIMAL (9, 2)  NULL,
    [converted_custom_client_rate_per_hour] DECIMAL (9, 2)  NULL,
    [custom_margin]                         DECIMAL (14, 4) NULL,
    [custom_client_rate_comment]            NVARCHAR (1000) NULL,
    [resource_row_id]                       BIGINT          NULL,
    [last_resource_row_sync_date_time]      DATETIME2 (7)   NULL,
    [shift_time_id]                         BIGINT          NULL,
    [support_model_id]                      BIGINT          NULL,
    [role_aspect_id]                        BIGINT          NULL,
    [row_number]                            INT             NULL,
    [frozen_data]                           BIT             DEFAULT ((0)) NULL
);
GO

