CREATE TABLE [data_in].[valuation_version] (
    [id]                                             BIGINT          NULL,
    [name]                                           NVARCHAR (500)  NULL,
    [valuation_id]                                   BIGINT          NULL,
    [start_date]                                     DATE            NULL,
    [end_date]                                       DATE            NULL,
    [status]                                         NVARCHAR (100)  NULL,
    [valuation_type]                                 NVARCHAR (100)  NULL,
    [active_version]                                 BIT             NULL,
    [discount_percentage]                            DECIMAL (9, 2)  NULL,
    [yearly_salary_rise_percentage]                  DECIMAL (9, 2)  NULL,
    [contingency_percentage]                         DECIMAL (9, 2)  NULL,
    [security_percentage]                            DECIMAL (9, 2)  NULL,
    [margin_percentage]                              DECIMAL (14, 4) NULL,
    [billability_percentage]                         DECIMAL (9, 2)  NULL,
    [other_cost_percentage]                          DECIMAL (9, 2)  NULL,
    [net_margin_percentage]                          DECIMAL (14, 4) NULL,
    [total_cost]                                     DECIMAL (19, 2) NULL,
    [original_price]                                 DECIMAL (19, 2) NULL,
    [discounted_price]                               DECIMAL (19, 2) NULL,
    [creation_at]                                    DATETIME2 (7)   NULL,
    [modified_at]                                    DATETIME2 (7)   NULL,
    [created_by]                                     BIGINT          NULL,
    [modified_by]                                    BIGINT          NULL,
    [version_number]                                 INT             NULL,
    [yearly_salary_rise_cost]                        DECIMAL (19, 2) NULL,
    [contingency_cost]                               DECIMAL (19, 2) NULL,
    [security_cost]                                  DECIMAL (19, 2) NULL,
    [calculation_date]                               DATETIME2 (7)   NULL,
    [delivery_leader_approve_ind]                    BIT             NULL,
    [delivery_leader_reviewer_id]                    BIGINT          NULL,
    [delivery_leader_review_time]                    DATETIME2 (7)   NULL,
    [resource_manager_approve_ind]                   BIT             NULL,
    [resource_manager_reviewer_id]                   BIGINT          NULL,
    [resource_manager_review_time]                   DATETIME2 (7)   NULL,
    [rejection_reason]                               NVARCHAR (2000) NULL,
    [reopen_reason]                                  NVARCHAR (2000) NULL,
    [account_manager_approve_ind]                    BIT             NULL,
    [account_manager_reviewer_id]                    BIGINT          NULL,
    [account_manager_review_time]                    DATETIME2 (7)   NULL,
    [financials_modification_date]                   DATETIME2 (7)   NULL,
    [account_manager_approve_action_expiration_ind]  BIT             NULL,
    [account_manager_approve_action_expiration_date] DATETIME2 (7)   NULL,
    [business_case_description]                      NVARCHAR (1000) NULL,
    [fixed_price_ind]                                BIT             NULL,
    [third_party_cost]                               DECIMAL (19, 2) NULL,
    [demand_type]                                    NVARCHAR (100)  NULL,
    [fixed_type]                                     NVARCHAR (100)  NULL,
    [archived_ind]                                   BIT             NULL,
    [delivery_director_approve_ind]                  BIT             NULL,
    [delivery_director_reviewer_id]                  BIGINT          NULL,
    [delivery_director_review_time]                  DATETIME2 (7)   NULL,
    [delivery_director_review_required]              BIT             NULL,
    [suggested_margin]                               DECIMAL (14, 4) NULL,
    [total_actual_cost]                              DECIMAL (19, 2) NULL,
    [total_actual_price]                             DECIMAL (19, 2) NULL,
    [total_actual_discounted_price]                  DECIMAL (19, 2) NULL,
    [total_actual_net_margin_percentage]             DECIMAL (14, 4) NULL,
    [total_estimated_cost]                           DECIMAL (19, 2) NULL,
    [total_estimated_price]                          DECIMAL (19, 2) NULL,
    [total_estimated_discounted_price]               DECIMAL (19, 2) NULL,
    [total_estimated_net_margin_percentage]          DECIMAL (14, 4) NULL,
    [cr_effective_date]                              DATE            NULL,
    [actual_source_type]                             NVARCHAR (100)  NULL,
    [total_contract_discounted_price]                DECIMAL (19, 2) NULL,
    [total_contract_net_margin_percentage]           DECIMAL (14, 4) NULL,
    [total_baseline_cost]                            DECIMAL (19, 2) NULL,
    [total_baseline_price]                           DECIMAL (19, 2) NULL,
    [total_baseline_discounted_price]                DECIMAL (19, 2) NULL,
    [total_baseline_net_margin_percentage]           DECIMAL (14, 4) NULL
);
GO

